### ISSUE TITLE
ISSUE: funkagent should adopt formal function response message format

### ISSUE THREAD

**Issue by merefield** [aurelio-labs/funkagent#8]
I've noticed an issue with `funkagent`, it's not using the formal function response message format described in the documentation

https://platform.openai.com/docs/guides/gpt/function-calling

The format should be

```
      messages.append(
          {
              "role": "function",
              "name": function_name,
              "content": function_response,
          }
      )  # extend conversation with function response
```

But instead it's using the `assistant` role and missing the function `name`:

https://github.com/aurelio-labs/funkagent/blob/a7305d3c5baba57b9adf7d5b15d02eeeccad7fba/funkagent/agents.py#L82

This is not critical, it appears, but it's a tidy up and may facilitate dropping the "answer is" text for a tiny token win.  And we don't know if this will become more important in the future.

An equivalent change is illustrated below on my Ruby on Rails agent:

https://github.com/merefield/discourse-chatbot/pull/36/commits/6b89b62fd0cf240240cf71d1a25477c391ad74a8

I've PR'd on #9

**Comment by jamescalam** [comment]
Fixed with #9
